In [13]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.model_selection import train_test_split

In [14]:
data=pd.read_csv(r"C:\Users\sathv\LU\datasets\train.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
le=preprocessing.LabelEncoder()
data['Sex']=le.fit_transform(data['Sex'])
data['Embarked']=le.fit_transform(data['Embarked'])
data=data.drop(['Ticket','Cabin','PassengerId','Name'],axis=1)

In [16]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [23]:
DV=['Survived','Pclass','Sex','SibSp','Parch','Embarked']

In [38]:
def SVM(name):
    y=data[name]
    x=data.drop(name,axis=1)
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
    clf=svm.SVC(gamma=0.01,C=100)
    clf.fit(x_train,y_train)
    y_pred=clf.predict(x_test)
    print(f"Accuracy score and Confusion matrix with {name} and other Independent Variables is:")
    print(accuracy_score(y_test,y_pred,normalize=True))
    cm=confusion_matrix(y_test,y_pred)
    print(cm)
    print("The correct values predicted are",np.trace(cm),"out of total values",np.sum(cm),"Giving accuracy of",np.trace(cm)/np.sum(cm),"\n\n")

In [39]:
for name in DV:
    SVM(name)

Accuracy score and Confusion matrix with Survived and other Independent Variables is:
0.6853932584269663
[[80 25]
 [31 42]]
The correct values predicted are 122 out of total values 178 Giving accuracy of 0.6853932584269663 


Accuracy score and Confusion matrix with Pclass and other Independent Variables is:
0.9213483146067416
[[43  4  0]
 [ 3 28  4]
 [ 0  3 93]]
The correct values predicted are 164 out of total values 178 Giving accuracy of 0.9213483146067416 


Accuracy score and Confusion matrix with Sex and other Independent Variables is:
0.6853932584269663
[[37 26]
 [30 85]]
The correct values predicted are 122 out of total values 178 Giving accuracy of 0.6853932584269663 


Accuracy score and Confusion matrix with SibSp and other Independent Variables is:
0.797752808988764
[[110  14   0   0   0   0   0]
 [ 13  25   2   0   0   0   0]
 [  2   1   1   0   0   0   0]
 [  0   2   1   2   1   0   0]
 [  0   0   0   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   