In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import *
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv(r"C:\Users\sathv\LU\datasets\train.csv")

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data1=data.drop(['Cabin','Ticket','Name','PassengerId'],axis=1)

In [5]:
data1

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
884         0       2    male  27.0      0      0  13.0000        S
885         1       1  female  19.0      0      0  30.0000        S
886         0       3  female  45.0      1      2  23.4500        S
887         1       1    male  26.0      0      0  30.0000        C
888         0       3    male  32.0      0      0   7.7500        Q

[889 rows x 8 columns]

In [6]:
le=preprocessing.LabelEncoder()
data1['Sex']=le.fit_transform(data1['Sex'])
data1['Embarked']=le.fit_transform(data1['Embarked'])

In [7]:
data1.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [8]:
data1

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
884         0       2    1  27.0      0      0  13.0000         2
885         1       1    0  19.0      0      0  30.0000         2
886         0       3    0  45.0      1      2  23.4500         2
887         1       1    1  26.0      0      0  30.0000         0
888         0       3    1  32.0      0      0   7.7500         1

[889 rows x 8 columns]

In [9]:
data1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [10]:
IDV=['Survived', 'Pclass', 'Sex',  'SibSp', 'Parch','Embarked']

In [26]:
def NaiveBayes(name):
    y=data1[name]
    X=data1.drop(name,axis=1)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
    clf=BernoulliNB()
    y_pred=clf.fit(X_train,y_train).predict(X_test)
    print(f"Accuracy Score and Confusion matrix of {name} with other Independent variables")
    print(accuracy_score(y_test,y_pred,normalize=True))
    cm=confusion_matrix(y_test,y_pred)
    print(cm)
    print("The total correct values predicted are ",np.trace(cm),"out of total values ",np.sum(cm),"giving accuracy of ",np.trace(cm)/np.sum(cm))
    print("\n\n")

In [27]:
for name in IDV:
    NaiveBayes(name)

Accuracy Score and Confusion matrix of Survived with other Independent variables
0.7715355805243446
[[131  26]
 [ 35  75]]
The total correct values predicted are  206 out of total values  267 giving accuracy of  0.7715355805243446



Accuracy Score and Confusion matrix of Pclass with other Independent variables
0.5917602996254682
[[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
The total correct values predicted are  158 out of total values  267 giving accuracy of  0.5917602996254682



Accuracy Score and Confusion matrix of Sex with other Independent variables
0.7453183520599251
[[ 49  49]
 [ 19 150]]
The total correct values predicted are  199 out of total values  267 giving accuracy of  0.7453183520599251



Accuracy Score and Confusion matrix of SibSp with other Independent variables
0.6891385767790262
[[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]